# =============================================================================
# CONFIGURACIÓN ETL - AJUSTADA PARA TU SCHEMA SQL REAL
# =============================================================================

# Configuración de Excel
excel:
  folder: 'C:/ruta/a/tu/carpeta'
  extensions:
    - '.xlsx'
    - '.xls'

# Configuración de base de datos
database:
  chunk_size: 500  # Reducido por si hay problemas de decimal
  if_exists: 'append'

# NO normalizar columnas - usar nombres exactos de SQL Server
normalize_columns: false

# Mapeo de hojas Excel a tablas SQL (usar nombres exactos con espacios)
table_mappings:
  'Centro MTBT': 'Centro MTBT'
  'Equipos de maniobras': 'Equipos de maniobras'
  'Interrupciones': 'Interrupciones'

# Configuración específica por tabla
tables:
  'Centro MTBT':
    # CRÍTICO: Mapear columnas Excel a columnas SQL EXACTAS
    column_mappings:
      # Si Excel tiene esto...               → SQL Server espera esto...
      'Código Centro MT/BT': 'Código Centro de transformación MT/BT'
      'Codigo Centro MT/BT': 'Código Centro de transformación MT/BT'
      'Código Centro de transformación MT/BT': 'Código Centro de transformación MT/BT'
      # KVA se mantiene igual
      'KVA instalado por transformador': 'KVA instalado por transformador'
      # UTM se mantienen igual
      'UTM Centro MT/BT Norte': 'UTM Centro MT/BT Norte'
      'UTM Centro MT/BT Oeste': 'UTM Centro MT/BT Oeste'
      # Otras columnas que podrían existir en Excel
      'Equipo aguas arriba': 'Equipo aguas arriba'
      'Propietario': 'Propietario'
    
    # Tipos de datos - AJUSTADOS para evitar overflow
    column_types:
      'KVA instalado por transformador': 'numeric'  # Será truncado por DECIMAL(6,4)
      'UTM Centro MT/BT Norte': 'integer'
      'UTM Centro MT/BT Oeste': 'integer'
    
    # Validación de rangos (advertir pero no bloquear)
    data_validation:
      'KVA instalado por transformador':
        max_value: 99.9999  # Límite por DECIMAL(6,4) - REVISAR SQL!
        warning: "KVA mayor a 99.9999 será truncado por DECIMAL(6,4) en SQL"
      'UTM Centro MT/BT Norte':
        max_value: 2147483647  # Límite INT
      'UTM Centro MT/BT Oeste':
        max_value: 2147483647

  'Equipos de maniobras':
    column_mappings:
      # Manejar diferentes variaciones de capitalización
      'Código de Equipo': 'Código de equipo'
      'Código de equipo': 'Código de equipo'
      'Codigo de Equipo': 'Código de equipo'
      'Codigo de equipo': 'Código de equipo'
      # Otros campos
      'Tipo de equipo': 'Tipo de equipo'
      'Tipo de Equipo': 'Tipo de equipo'
      'Código de subestación': 'Código de subestación'
      'Codigo de Equipo Aguas Arriba': 'Codigo de Equipo Aguas Arriba'
      'Nivel de tensión': 'Nivel de tensión'
      'Nivel de tension': 'Nivel de tensión'
      'Corriente máxima': 'Corriente máxima'
      'Corriente maxima': 'Corriente máxima'
      'UTM Equipo Norte': 'UTM Equipo Norte'
      'UTM Equipo Oeste': 'UTM Equipo Oeste'
    
    column_types:
      'Nivel de tensión': 'numeric'  # Será truncado por DECIMAL(3,2)
      'Corriente máxima': 'integer'
      'UTM Equipo Norte': 'integer'
      'UTM Equipo Oeste': 'integer'
    
    data_validation:
      'Nivel de tensión':
        max_value: 9.99  # Límite por DECIMAL(3,2) - REVISAR SQL!
        warning: "Tensión mayor a 9.99 kV será truncada por DECIMAL(3,2) en SQL"
      'Corriente máxima':
        max_value: 2147483647

  'Interrupciones':
    column_mappings:
      # Campos de fecha
      'Fecha y Hora_Inicio': 'Fecha y Hora_Inicio'
      'Fecha y Hora Inicio': 'Fecha y Hora_Inicio'
      'Fecha y Hora_Cierre': 'Fecha y Hora_Cierre'
      'Fecha y Hora Cierre': 'Fecha y Hora_Cierre'
      'Fecha Notificacion al Usuario': 'Fecha Notificacion al Usuario'
      'Fecha Notificación al Usuario': 'Fecha Notificacion al Usuario'
      # Campos de texto
      'Causa': 'Causa'
      'Origen del evento': 'Origen del evento'
      'Código de Equipo': 'Código de Equipo'
      'Codigo de Equipo': 'Código de Equipo'
      'Enlace Medio de Notificacion a los Usuarios': 'Enlace Medio de Notificacion a los Usuarios'
      'Observaciones': 'Observaciones'
      'ID_Interrupcion': 'ID_Interrupcion'
      'ID Interrupcion': 'ID_Interrupcion'
      # CRÍTICO: La columna transformada debe usar el nombre SQL exacto
      'Primer Código de Equipo': 'CódigoDePrimerEquipo'
      'Primer Codigo de Equipo': 'CódigoDePrimerEquipo'
    
    column_types:
      'Fecha y Hora_Inicio': 'datetime'
      'Fecha y Hora_Cierre': 'datetime'
      'Fecha Notificacion al Usuario': 'datetime'  # SQL es DATE pero datetime funciona
    
    # Transformación para crear CódigoDePrimerEquipo
    transformations:
      - type: 'split_first'
        source: 'Código de Equipo'
        target: 'CódigoDePrimerEquipo'  # USAR NOMBRE SQL EXACTO
        delimiter: ','

# Configuración de logging
logging:
  level: 'DEBUG'  # Usar DEBUG para ver todos los detalles
  directory: 'logs'